import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import SideNavbar from "./Components/SideNavbar";
import { Providers } from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Providers>
         <div className=" h-screen bg-radial-[at_50%_75%] from-[#CAE0F0] via-[#DBE5F5] to-[#E1E8F6] to-90% ">
            <Navbar className="overflow" />
          <div className="flex  flex-1 h-[calc(100vh-4rem)]">
          <SideNavbar />
            <main className="p-4 flex-1 overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
       </Providers>
      </body>
    </html>
  );
}
